# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DataMovement.sln'
  solution1: 'DataMovement_k.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'Azure Storage DM Dev(a0d901ba-9956-4f7d-830c-2d7974c36666)'
    ScriptType: 'InlineScript'
    Inline: |
      Enable-AzureRmAlias
      $account=Get-AzStorageAccount -ResourceGroupName DMBuild -Name dmlibbuild
      Get-AzureStorageContainer -Context $account.Context

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:Rebuild /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'

- task: BatchScript@1
  inputs:
    filename: '.\netcore\Build.cmd'
    arguments: '$(buildConfiguration)'
